### PR TITLE
Add RTL support

### PR DESCRIPTION
**Pull request by HasnAr**
to support right to left scrollable tab view

### CODE REVIEW

**Comment by asfktz** [comment]
Would like to confirm that this fix works on `0.8.0`. tested on iOS.

**Comment by asfktz** [comment]
Hmm.. seems like it not working property on android..

**Comment by asfktz** [comment]
Interestingly enough, taking only the changes in  /DefaultTabBar.js

Works on both Android and iOS

**Comment by Shabnam-Veranloo** [comment]
not support layout RTL in android

**Comment by Shtibel** [comment]
RTL on android Dose not work
Any updates?

**Pull request closed without merging**
