### PR TITLE
Pass all child props to tabs

### PR DESCRIPTION
**Pull request by gpEscrivo**
Allows you to pass / access any prop though tabProps[i]. This allows more flexibility in custom TabBars. 

For example, different color per tabs, notifications on tabs, etc..

### CODE REVIEW

**Comment by skv-headless** [comment]
Could you write a snippet how to use it?

**Comment by gpEscrivo** [comment]
Sure, you can pass basically anything, but here are two very stripped down examples:

**Tab bar with text and icon:**

```
<ScrollableTabView
  renderTabBar={() => <TabBarWithTextAndIcon/>}
>
  <TabOne
    tabLabel={"Profile"}
    tabIcon={"user"}
  />
  <TabTwo
    tabLabel={"Settings"}
    tabIcon={"gear"}
  />
</ScrollableTabView>

//TabBarWithTextAndIcon render function

render() {
  const { tabs, tabProps } = this.props;

  return (
    <View style={[styles.tabs, this.props.style]}>
          {tabs.map((tab, i) => {
            const { tabIcon } = tabProps[i];
            
            return (
              <TouchableOpacity
                key={i}
                onPress={() => this.props.goToPage(i)}
                style={styles.tab}
              >
                <Icon
                  name={tabIcon}
                  size={30}
                  color={this.props.activeTab === i ? 'rgb(59,89,152)' : 'rgb(204,204,204)'}
                />
                <Text numberOfLines={1} style={styles.text}>{tab.toUpperCase()}</Text>
              </TouchableOpacity>
            )
          })}
      </View>
  )
}
```

**Tab bar with notifications:**


```
<ScrollableTabView
  renderTabBar={() => <TabBarWithNotifications/>}
>
  <TabOne
    tabLabel={"Profile"}
    notifications={20}
  />
  <TabTwo
    tabLabel={"Settings"}
    notifications={10}
  />
</ScrollableTabView>

//TabBarWithNotifications render function:

render() {
  const { tabs, tabProps } = this.props;

  return (
    <View style={[styles.tabs, this.props.style]}>
          {tabs.map((tab, i) => {
            const { notifications } = tabProps[i];
            
            return (
              <TouchableOpacity
                key={i}
                onPress={() => this.props.goToPage(i)}
                style={styles.tab}
              >
                <Text numberOfLines={1} style={styles.text}>{tab.toUpperCase()}</Text>
                <View style={styles.redBlob}>
                  <Text style={styles.whiteText}>
                    {notifications}
                  </Text>
                </View>
              </TouchableOpacity>
            )
          })}
      </View>
  )
}

```

**Comment by skv-headless** [comment]
Sorry for delay. Maybe instead of passing all props make special property ```tabProps``` and pass only them?

**Comment by woshi82** [comment]
`tabLabel={{icon: 'ios-people', text: '资讯'}}` can pass all props i want

**Comment by pipo24** [comment]
@skv-headless any reason this hasn't been accepted?
Would be really useful to be able to customise the TabBar Styles easily.
Thanks

**Comment by ptomasroos** [comment]
This PR is very outdated, hence if this changes are still needed feel free to rebase them on top of master and open a new PR. From now on there will be faster feedback on issues and pull requests.

**Pull request closed without merging**
