### PR TITLE
feature: add icon support to tabs

### PR DESCRIPTION
**Pull request by kennethlynne**
Breaking change, as it changes how tabs are initialised

### CODE REVIEW

**Comment by skv-headless** [comment]
Guys there are already 2 ways to do it. I don't want one more.

**Comment by skv-headless** [comment]
@kennethlynne @denistakeda I think you are right. But I want to change `tabLabel` property to `label` which can be text or react component. What do you think?

**Comment by denistakeda** [comment]
@skv-headless The issue here is that one has to set `tabLabel` attribute to his own component. It could be a big problem if you use this library with Typescript like we are, also it's not very clear api.

I can propose to use special Tab component with it's own props (as many as you need). Here is an example of popular web version: http://www.material-ui.com/#/components/tabs

It can not to break api (because for top level component it doesn't matter to which component this props sat by)

**Comment by denistakeda** [comment]
For now it's quite hard to implement icons for tabs. For do this one has to implement his own tab bar (like `FacebookTabBar` in the examples). And if you want to have 3 different tab bars in your app you have to implement it 3 times.

**Comment by skv-headless** [comment]
Could you please explain why it is difficult to use with typescript?

**Comment by denistakeda** [comment]
@skv-headless with typescript you can't send undeclared property to the component. So, you have to declare property `tabLabel` for each component you wanna use with tabs. It breaks component's semantic and can confuse somebody who doesn't know that this component uses inside Tabs.

**Comment by hugohow** [comment]
+1

**Comment by skv-headless** [comment]
I'm still thinking that it should be only one property for tab instead of `tabLabel`, `icon` and `activeIcon`.

**Pull request closed without merging**
