### PR TITLE
Fixes ListView cancelled horizontal scroll onRefresh

### LINKED ISSUE #541: [Android] ListView onRefresh cancelled by horizontal scroll bug
Pull down to refresh cancels when the slightest horizontal scroll happens, only seen this on android. Horizontal scrolling seems to be disabled when pulling to refresh on iOS. Is there already a solution to this? I have read about the issue but nothing seems to be solved yet.

### PR DESCRIPTION
**Pull request by krailler**
Fixes #541

### CODE REVIEW

**Comment by imbudhiraja** [comment]
Hi @krailler , 
 this.scrollView.scrollTo({ x, animated: false }) returns undefined every time i set initial page =1 or any tab index. Can you please check this.

const scrollFn = () => {
        if (this.scrollView && Platform.OS === 'android') {
          const x = this.props.initialPage * this.state.containerWidth;
       this.scrollView.scrollTo({ x, animated: false });
         if(x) this.scrollView.scrollTo({ x, animated: false });
        }
      };

**Comment by krailler** [comment]
@imbudhiraja Try now. :)

**Comment by imbudhiraja** [comment]
Fixes #523 as well.

**Comment by krailler** [comment]
@skv-headless See this.

**Comment by skv-headless** [comment]
I was forced to move to `ScrollView` I think when those guys will ask to return `ScrollView`. So I'm still not sure what to do :disappointed:

**Comment by AndrewJack** [comment]
@skv-headless Why did you move to `ScrollView` rather than `ViewPagerAndroid`?

**Comment by ptomasroos** [comment]
This PR is very outdated, hence if this changes are still needed feel free to rebase them on top of master and open a new PR. From now on there will be faster feedback on issues and pull requests.

**Pull request closed without merging**
