### PR TITLE
Active and Inactive text/font sizes feature

### PR DESCRIPTION
**Pull request by Amurmurmur**
Set different text/font size when tab is active and inactive for Default and Scrollable tabbars.

### CODE REVIEW

**Comment by skv-headless** [comment]
Thanks. I'm just thinking that we can make `activeTextStyle` property to pass any style.

**Comment by skv-headless** [comment]
@Amurmurmur could you please update PR?

**Comment by pvinis** [comment]
why a text style, and not a way to put a whole element there? just make the touchable, and inside, let us put a component we want.

**Comment by ptomasroos** [comment]
This PR is very outdated, hence if this changes are still needed feel free to rebase them on top of master and open a new PR. From now on there will be faster feedback on issues and pull requests.

**Pull request closed without merging**
