### PR TITLE
API controlled goToPage functionality

### PR DESCRIPTION
**Pull request by sospedra**
This PR creates a `tabContentProps` with `goToPage`, `ownPosition` and `tabs` and merge it with the `SceneComponent` children props.

The main benefit is the possibility to navigate programatically instead of relying only on the `TabBarComponent` 🤓 🖥 

There's an example attached showing the new feature. Find it at `examples/StepperBar`.

Updated `README` and fixed `eslint` issues are included too 👌

### CODE REVIEW

**Comment by sospedra** [comment]
@skv-headless 🙏

**Comment by sospedra** [comment]
@skv-headless 😢

**Comment by skv-headless** [comment]
@sospedra sorry that I didn't answer before. I don't think that API that you provided is easier or more intuitive.

**Comment by sospedra** [comment]
Maybe not. But it enables another dimension: working inside the tab. Did you check the example?

**Comment by skv-headless** [comment]
I've just added to docs https://github.com/skv-headless/react-native-scrollable-tab-view#changing-between-tabs. Is it the same thing what you want to do?

**Comment by sospedra** [comment]
I don't think is the same. In your example you're adding a new Tab which includes a button to move to the 0 position; and that's not programatically because the trigger action cames from pressing a button.

With my PR you can actually manage the whole navigation inside any Tab. There are strongly different functionalities. Here's a gif of the example I added to the PR.

stepper

**Comment by sospedra** [comment]
I can make a more clear documentation if you feel like is hard to understand ;)

**Comment by skv-headless** [comment]
everything is possible to do with current implementation. I guess I need to write more docs for that.

**Comment by gopaldevra** [comment]
Try this
1. Take the ref of the ScrollableTabView like this
```
 <ScrollableTabView
          initialPage={0}

          ref='tabView'
</ScrollableTabView>

```
2.

```
componentDidMount() {
    let self = this;

    console.log(this.refs);
    setTimeout(() => {
      // self.setState({ index: 1 });
      self.refs.tabView.goToPage(1);
      // alert(self.state.index);
    }, 300);
  }
```

**Comment by ptomasroos** [comment]
This PR is very outdated, hence if this changes are still needed feel free to rebase them on top of master and open a new PR. From now on there will be faster feedback on issues and pull requests.

**Pull request closed without merging**
