### PR TITLE
Add Collapsable Bar

### PR DESCRIPTION
**Pull request by tibbus**
add collapsable bar functionality
* fix old linting errors
* add collpasableBar api props
* replace the Container View with a ScrollView to allow collapsable functionality
* use collapasable functionality just if it's passed in props
* add collapsable to Examples

CONS: When collapsableBar is active we cannot support pre-loading the TABs View as it will break the vertical scroll, so at each TAB click the content will be re-rendered.

DEMO : 
https://github.com/tibbus/react-native-scrollable-tab-view/blob/demo/demo_images/demo-collapsable.gif

ISSUES : [638](https://github.com/skv-headless/react-native-scrollable-tab-view/issues/638)  [628](https://github.com/skv-headless/react-native-scrollable-tab-view/issues/628)  [385](https://github.com/skv-headless/react-native-scrollable-tab-view/issues/385)

### CODE REVIEW

**Comment by cham1985** [comment]
Hi, at each TAB click the content will be re-rendered, Can this problem be solved in the future?

**Comment by tibbus** [comment]
Not sure, I was thinking a bit about it and didn't find any easy fix.

I didn't looked too much into it as it's not a big issue for me and this is not even merged yet.

**Comment by cham1985** [comment]
could the childElement of the ScrollableTabView be a  ListView ?

**Comment by cham1985** [comment]
Hi, i changed View to Listview as a childElement of the  ScrollableTabView, but i found the onEndReached func occured a wrong callback

**Comment by tibbus** [comment]
Not sure what do you mean ?  ScrollableTabView was already changed to a ScrollView in this PR .

So to have this effect CollapseBar, TabBar and the Content should be inside the same ScrollView as children so you can add stickyIndex to the TabBar

**Comment by cham1985** [comment]
getInitialState: function () {
        let ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
        return {
            dataSource: ds.cloneWithRows(this._genRows({})),
        };
    },

    _genRows: function (pressData) {
        let dataBlob = [];
        for (let ii = 0; ii < 30; ii++) {
            let pressedText = pressData[ii] ? ' (pressed)' : '';
            dataBlob.push('Row ' + ii + pressedText);
        }
        return dataBlob;
    },

    render() {
        const collapsableComponent = (
            <View>
                <Icon name='logo-apple' color='black' size={100} style={styles.topIcon}/>
                <Icon name='logo-android' color='#A4C639' size={100} style={styles.topIcon}/>
            </View>
        );

        return <ScrollableTabView collapsableBar={collapsableComponent}
                                  tabBarBackgroundColor="white"
                                  renderTabBar={() => <DefaultTabBar />}
        >
            <ListView
                tabLabel='IOS'
                scrollEnabled={false}
                dataSource={this.state.dataSource}
                renderRow={(rowData) => <Text style={{fontSize: 50}}>{rowData}</Text>}
                onEndReachedThreshold={50}
                scrollRenderAheadDistance={10}
                onEndReached={() => {
                    Log.log('CollapsableExample.js onEndReached')
                }
                }

            />
            <ListView
                tabLabel='Android'
                scrollEnabled={false}
                dataSource={this.state.dataSource}
                renderRow={(rowData) => <Text style={{fontSize: 50,}}>{rowData}</Text>}
                onEndReachedThreshold={50}
                scrollRenderAheadDistance={10}
                onEndReached={() => {
                    Log.log('CollapsableExample.js onEndReached')
                }
                }

            />
        </ScrollableTabView>;
    },
hi ,here is my changed code ,I don't know why the onEndReached function has been called back 11 times  ?

**Comment by davidpaulsson** [comment]
It's very much possible to build the tab bar on your own, see https://github.com/skv-headless/react-native-scrollable-tab-view/issues/628#issuecomment-324893658

**Comment by Kunsan16** [comment]
@tibbus hi，how can i use the collapsable bar ，It seems that author（skv-headless） dose not merge your fork？

**Comment by tibbus** [comment]
@Kunsan16 This pull request was not merged indeed. If you want to use it, you need to fork this PR, there's also an example in this PR of how to use it : 
https://github.com/skv-headless/react-native-scrollable-tab-view/pull/667/files#diff-dde318e73285bbdce77dae632bbe1be5R1

**Comment by JaxGit** [comment]
Appart from @cham1985 's issue, there is another one: 
as long as any of the tab contents under tabbar has reached the end and bounced, switch to another tab, scroll up before the CollapsableBar reaches the top and bounces, then switching tabs again will cause the CollapsableBar instantly collapse. The issue disappear afters scrolling to the very top.

**Comment by JaxGit** [comment]
excuse me @tibbus , how about this: 
```javascript
  renderSectionHeader(sectionData, sectionId, rowId) {
    if (sectionId == 0) {
      return null;
    }
    if (sectionId == 1) {
      return this.renderTabBar(tabBarProps);
      
    } else {
      return null;
    }
  }

  renderRow(rowData, sectionId, rowId) {
    if (sectionId == 0) {
      return <CollapsibleHeader/>

    } else if (sectionId == 1) {
      return this.renderScrollableContent();

    } else {
      return null;
    }
  }

  render() {
    return (
      <ListView
        style={{flex: 1}}
        renderSectionHeader={this.renderSectionHeader}
        renderRow={this.renderRow}
        dataSource = {this.ds.cloneWithRowsAndSections({0: [{0: 'rowData0'}], 1: [{0: 'rowData1'}]})}
        enableEmptySections
        stickyHeaderIndices = {[1]}
      />
    );
  }
```
then disable the nested ListView if it's in scrollable content, pass onEndReached to parent ListView for handling fetching more data.

I know this is dumb but at least it doesn't need to worry about the calculations. 
Before integrating with the lib, I combined yours and @davidpaulsson 's idea of rendering custom tabbar instead of rendering this.renderTabBar() for sectionId 1 sectionHeader, also setting renderTabBar={() => <View />} for `<ScrollableTabView />` and it seems to be working as well.

**Comment by tibbus** [comment]
@JaxGit 
I don't really follow what file is this or how it's working as I didn't looked into it anymore, but it looks like this pull request will NOT be merged.

So it's good to have here more examples / ways of how to implement this behavior so other people can find it.

**Comment by JaxGit** [comment]
Thank you @tibbus , I just found my code wrong. 
Now I know why in you solution for each TAB click the content will be re-rendered, as my code which is rendering `<ScrollableTabView />` instead of this.renderScrollableContent() already breaks the vertical scroll -- after vertical scrolling any tab content, all other tab contents have also scrolled ...

**Comment by Thanmai-C** [comment]
@tibbus the code that you shared works well but have a problem with it,
when i scroll it up the scrollHeader fixes to the top but when i try to change the tab, the scrollHeader that was fixed on top comes back to its old position and then changes the tab.
Is there any way to change the tab even while the scrollHeader is fixed on top.

**Comment by tibbus** [comment]
@mayupat13 you need the changes from this PR for that Example to work.

**Comment by Ekhui** [comment]
@tibbus  if i put the flatList into the ScrollableTabView its not working. like this``

**Comment by Ekhui** [comment]
@tibbus if i put the flatList into the ScrollableTabView its not working. like this

`<ScrollableTabView collapsableBar={collapsableComponent}                             
                                  renderTabBar={() => <DefaultTabBar/>}
        >
            <View tabLabel='iOS' style={{height:VALUE.height-100}}>
                <FlatList
                    showsVerticalScrollIndicator={false}
                    ref={'flatList'}
                    data={[{key: 'a'}, {key: 'b'}, {key: 'c'}, {key: 'd'}, {key: 'e'}, {key: 'f'},
                        {key: 'g'}, {key: 'h'}, {key: 'i'}, {key: 'j'}, {key: 'k'}, {key: 'l'}, {key: 'm'},
                        {key: 'n'}, {key: 'o'}, {key: 'p'}, {key: 'q'}, {key: 'r'}, {key: 's'}, {key: 't'},
                        {key: 'u'}, {key: 'v'}, {key: 'w'}, {key: 'x'}, {key: 'y'}, {key: 'z'}
                    ]}
                    keyExtractor={this._keyExtractor}
                    renderItem={this._renderItem}
                />
            </View>
            <View tabLabel='Android'>
                <FlatList
                    showsVerticalScrollIndicator={false}
                    ref={'flatList'}
                    data={[{key: 'a'}, {key: 'b'}, {key: 'c'}, {key: 'd'}, {key: 'e'}, {key: 'f'},
                        {key: 'g'}, {key: 'h'}, {key: 'i'}, {key: 'j'}, {key: 'k'}, {key: 'l'}, {key: 'm'},
                        {key: 'n'}, {key: 'o'}, {key: 'p'}, {key: 'q'}, {key: 'r'}, {key: 's'}, {key: 't'},
                        {key: 'u'}, {key: 'v'}, {key: 'w'}, {key: 'x'}, {key: 'y'}, {key: 'z'}
                    ]}
                    keyExtractor={this._keyExtractor}
                    renderItem={this._renderItem}
                />
            </View>
        </ScrollableTabView>;`

**Comment by ptomasroos** [comment]
This PR is very outdated, hence if this changes are still needed feel free to rebase them on top of master and open a new PR. From now on there will be faster feedback on issues and pull requests.

**Comment by ravisojitra** [comment]
Is there solution to this problem? I'm heavily relying on this package and want collapsible header but not able to. Please Help!

**Comment by decodedmrq** [comment]
@Tritty I'm facing problem, 
1. Tab with FlastList component is not fixed on the top.
2. And Not sliding from Tab (has FlastList) to another tab.

**Comment by zyslife** [comment]
You can try the [react-native-head-tab-view.](https://github.com/zyslife/react-native-head-tab-view)
(tabs with collapsible header)

**Comment by ugrdursun** [comment]
Hello 

> Is there solution to this problem? I'm heavily relying on this package and want collapsible header but not able to. Please Help!

Have you found the solution ?

**Pull request closed without merging**
