### PR TITLE
Fixed initialPage underlineStyle

### PR DESCRIPTION
**Pull request by JohnProg**
The first time, the underlineStyle is not shown.screen shot 2018-01-27 at 12 59 38 am

### CODE REVIEW

**Comment by numez** [comment]
I've fixed with this PR https://github.com/skv-headless/react-native-scrollable-tab-view/pull/824

**Comment by jamessawyer** [comment]
when will  this PR merge?

**Comment by spuchetavm** [comment]
We are waiting too.

**Comment by lizhuoyuan** [comment]
who has idea?

**Comment by onceMu** [comment]
This maybe cause other bug.The tab isn't in the correct position.

**Comment by VesperDev** [comment]
This Works thanks

**Comment by ptomasroos** [comment]
Fixed in latest release

**Pull request closed without merging**
