### PR TITLE
Scrollable multiple tab selection issue fixed

### PR DESCRIPTION
**Pull request by pandiaraj44**
In android M versions, The scrollable tab was not working properly. 

For example, let us take 4 tabs. When we selecting 4th tab the underline not getting moved. It's due to scroll offset value. So I have reduced the offset value by 0.1%.

screenshot_20161216-204755

screenshot_20161216-204817

### CODE REVIEW

**Comment by pandiaraj44** [comment]
cc @skv-headless

**Comment by skv-headless** [comment]
My nexus 5 is on marshmallow I have not seen this issue. What `offset.value` do you have?

**Comment by pandiaraj44** [comment]
**OnSelect**
**Tab 1** offset value: 0
**Tab 2** offset value: 0.9999999682108561
**Tab 3** offset value: 1.9999999364217123
**Tab 4** offset value: 3.0000001271565755

While selecting 4th tab the offset value goes to 3.0003 instead of 2.9999. So that the Math.floor given value as 3. It will change the entire position and underline view was updated with previous position(Tab 3).

This may due to screen size/ tab title width.

Tested Android Version - 23, Device- Nexus 5

**Comment by skv-headless** [comment]
Maybe we can just change `Math.floor(offset.value)` to `Math.round(offset.value)` or I'm wrong?

**Comment by pandiaraj44** [comment]
I have tried with Math.round & Math.ceil but it's not working. 

FYI..
//This pageOffset is getting wrong
 const pageOffset = offset.value % 1;

**Comment by pandiaraj44** [comment]
@skv-headless Can you please look at on this?.

**Comment by ptomasroos** [comment]
This PR is very outdated, hence if this changes are still needed feel free to rebase them on top of master and open a new PR. From now on there will be faster feedback on issues and pull requests.

**Pull request closed without merging**
