### PR TITLE
Compatibility with react-native-web

### PR DESCRIPTION
**Pull request by amoghbanta**
Hey,
We have a use case where we need tab bars on web and we use react-native for it and transpile it using [react-native-web](https://github.com/necolas/react-native-web).
while using it with react-native-web I was getting an error "not able to find button" because web doesn't read '.ios.js/.android.js/.windows.js' so I have added Button.js which works seamlessly with react-native-web.
So, now this awesome library runs on web too. 😄

### CODE REVIEW

**Comment by skv-headless** [comment]
1) I'm a little bit afraid to have `Button.js` file because it means both platform in `react-native`. I'm not fully aware how react-native packager works. Please point documentation for react-native-web about it
2) please squash commits

**Comment by vaukalak** [comment]
I think that file should be named `Button.web.js`, right now there's no official convention for naming, please follow this topic: https://github.com/necolas/react-native-web/issues/488

**Comment by vaukalak** [comment]
@amoghbanta @skv-headless as you can see from issue I've mentioned `.web.js` extension is a standard. So to complete this issue please rename the file to `Button.web.js`: https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md#web-specific-code

**Comment by ptomasroos** [comment]
This PR is very outdated, hence if this changes are still needed feel free to rebase them on top of master and open a new PR. From now on there will be faster feedback on issues and pull requests.

**Pull request closed without merging**
