### PR TITLE
Severe issue: 481 reproduction. React Update is needed.

### PR DESCRIPTION
**Pull request by bogomazov**
I would really appreciate a fix of this issue asap as I heavily rely on this component. =)
Issue appears on the later react package version.
related #481 #478

### CODE REVIEW

**Comment by skv-headless** [comment]
It is working fine for me except for the key warning. Checked on ios and android.

**Comment by bogomazov** [comment]
Just to clarify, did you npm install a newer version of reactjs? If you use the current one it doesn't break.

**Comment by skv-headless** [comment]
Yes. "react@^15.3.2" in node modules

**Comment by bogomazov** [comment]
And I assume you also "npm installed" it(i didn't push node_modules, so its
is required thats you do it manually in your local folder)... I don't have
ideas as to why it doesn't get reproduced on your machine...

**Comment by skv-headless** [comment]
@bogomazov what do you use? I still cant reproduce. Call me in skype (headless_666) when you have time.

**Comment by ptomasroos** [comment]
This PR is very outdated, hence if this changes are still needed feel free to rebase them on top of master and open a new PR. From now on there will be faster feedback on issues and pull requests.

**Pull request closed without merging**
