### PR TITLE
Fixes for android

### PR DESCRIPTION
**Pull request by xuanheScript**

### CODE REVIEW

**Comment by whyming** [comment]
I just need this,tks!

**Comment by seftonmonk** [comment]
why has this not gone in yet?

**Comment by brunobar79** [comment]
@Proyoyo  @skv-headless  Hey guys, do you think this  can be merged anytime soon?  Thanks!

**Comment by Proyoyo** [comment]
@brunobar79 I'm not the owner of the repo. I have no access to merge the PR.

**Comment by irrigator** [comment]
I have tested this PR on react native 0.53. It works.

**Comment by reimertz** [comment]
I can confirm this resolves the issues we had that eventually led us to implement our own tab view with a limited feature set. Will fork their repo and use put this PR on top of master. 

Great work @xuanheScript and @compojoom!

Would love to see this merged @skv-headless. <3

**Comment by uptophnarita** [comment]
@skv-headless Could you please merge this PR? Thanks!

**Comment by michaelampr** [comment]
@skv-headless this PR fixes the android bug with RN 0.55.4 as well. Please merge ❣️
Thanks @xuanheScript and @compojoom ✌️

**Comment by theRedster** [comment]
Please @skv-headless merge this. Fixes the problem so many people are having.

**Comment by callcter** [comment]
thx for your fix

**Comment by KristineTrona** [comment]
Why is this closed and not merged? Fixes the issue on android https://github.com/ptomasroos/react-native-scrollable-tab-view/issues/982

**Pull request closed without merging**
